import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/custom/Navbar/Navbar";
import { AuthProvider } from "@/firebase/AuthProvider";
import { ThemeProvider } from "@/components/theme/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "VortiQ Web | Next.js",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <AuthProvider>
                <body className={inter.className}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <div>
                            <div className="h-16">
                                <Navbar />
                            </div>
                            <div>
                                {children}
                            </div>
                        </div>
                    </ThemeProvider>
                </body>
            </AuthProvider>
        </html>
    );
}
